# IPPRAS

[c2]
common_name = ["Acetic"]
systematic = "ethanoic"

[c3]
common_name = ["Propionic"]
systematic = "propanoic"

[c3a2]
common_name = ["Propiolic"]
systematic = "propynoic"

[c3e2]
common_name = ["Acrylic"]
systematic = "prop-2-enoic"

[c4]
common_name = ["Butyric"]
systematic = "butanoic"

[c4c2]
common_name = ["Isocrotonic"]
systematic = "(2Z)-but-2-enoic"

[c4t2]
common_name = ["Crotonic"]
systematic = "(2E)-but-2-enoic"

[c5]
common_name = ["Valeric"]
systematic = "pentanoic"

[c6]
common_name = ["Caproic"]
systematic = "hexanoic"

[c6t3]
common_name = ["Hydrosorbic"]
systematic = "(3E)-hex-3-enoic"

[c6t2t4]
common_name = ["Sorbic"]
systematic = "(2E,4E)-hexa-2,4-dienoic"

[c7]
common_name = ["Oenanthic"]
systematic = "heptanoic"

[c8]
common_name = ["Caprylic"]
systematic = "octanoic"

[c9]
common_name = ["Pelargonic"]
systematic = "nonanoic"

[c10]
common_name = ["Capric"]
systematic = "decanoic"

[c10c4]
common_name = ["Obtusilic"]
systematic = "(4Z)-dec-4-enoic"

[c10e9]
common_name = ["Caproleic"]
systematic = "dec-9-enoic"

[c10c2c4]
common_name = ["cis,cis-Stillingic"]
systematic = "(2Z,4Z)-deca-2,4-dienoic"

[c10t2c4]
common_name = ["trans,cis-Stillingic"]
systematic = "(2E,4Z)-deca-2,4-dienoic"

[c10c2a4a6]
common_name = ["cis-Lachnophyllic"]
systematic = "(2Z)-dec-2-ene-4,6-diynoic"

[c10c2a4a6t8]
common_name = ["Z,E-Matricaric"]
systematic = "(2Z,8E)-deca-2,8-diene-4,6-diynoic"

[c10e2a4a6a8]
common_name = ["Dehydromatricaric"]
systematic = "(2E)-dec-2-ene-4,6,8-triynoic"

[c10t2a4a6t8]
common_name = ["Matricaric"]
systematic = "(2E,8E)-deca-2,8-diene-4,6-diynoic"

[c11]
common_name = ["Undecylic"]
systematic = "undecanoic"
[c11e10]
common_name = ["Undecylenic"]
systematic = "undec-10-enoic"

[c11c3a5a7a10]
common_name = ["Drosophilin C"]
systematic = "(3Z)-undec-3-ene-5,7,10-triynoic"

[c11c3a5a7e9e10]
common_name = ["Drosophilin D"]
systematic = "(3Z)-undeca-3,9,10-triene-5,7-diynoic"

[c12]
common_name = ["Lauric"]
systematic = "dodecanoic"

[c12t4]
common_name = ["Linderic"]
systematic = "(4Z)-dodec-4-enoic"

[c12c5]
common_name = ["Lauroleinic"]
systematic = "(5Z)-dodec-5-enoic"

[c12c9]
common_name = ["Lauroleic"]
systematic = "(9Z)-dodec-9-enoic"

[c12c3c5c7c9e11]
common_name = ["Ajenoic"]
systematic = "(3Z,5Z,7Z,9Z)-dodeca-3,5,7,9,11-pentaenoic"

[c13]
common_name = ["Tridecylic"]
systematic = "tridecanoic"

[c13c11]
common_name = ["Isotridecenoic"]
systematic = "(11Z)-tridec-11-enoic"

[c13c3c5a7a9a11]
common_name = ["Isomycomycin"]
systematic = "(3Z,5Z)-trideca-3,5-diene-7,9,11-triynoic"

[c13t3c5e7e8a10a12]
common_name = ["Mycomycin"]
systematic = "(3E,5Z)-trideca-3,5,7,8-tetraene-10,12-diynoic"

[c14]
common_name = ["Myristic"]
systematic = "tetradecanoic"

[c14c4]
common_name = ["Tsuzuic"]
systematic = "(4Z)-tetradec-4-enoic"

[c14c5]
common_name = ["Physeteric"]
systematic = "(5Z)-tetradec-5-enoic"

[c14c9]
common_name = ["Myristoleic"]
systematic = "(9Z)-tetradec-9-enoic"

[c14t9]
common_name = ["Myristelaidic"]
systematic = "(9E)-tetradec-9-enoic"

[c14t3c5]
common_name = ["Megatomic", "Megatomoic"]
systematic = "(3E,5Z)-tetradeca-3,5-dienoic"

[c14c5c8]
common_name = ["Goshuyic"]
systematic = "(5Z,8Z)-tetradeca-5,8-dienoic"

[c14t2t4a8a10]
common_name = ["Anacyclic"]
systematic = "(2E,4E)-tetradeca-2,4-diene-8,10-diynoic"

[c16]
common_name = ["Palmitic"]
systematic = "hexadecanoic"

[c16c11]
common_name = ["Palmitvaccenic"]
systematic = "(11Z)-hexadec-11-enoic"

[c16t11]
common_name = ["Lycopodic"]
systematic = "(11E)-hexadec-11-enoic"

[c16t2]
common_name = ["Gaidic"]
systematic = "(2E)-hexadec-2-enoic"

[c16c6]
common_name = ["Sapienic"]
systematic = "(6Z)-hexadec-6-enoic"

[c16a7]
common_name = ["Palmitolic"]
systematic = "hexadec-7-ynoic"
[c16c7]
common_name = ["Hypogeic"]
systematic = "(7Z)-hexadec-7-enoic"

[c16c9]
common_name = ["Palmitoleic"]
systematic = "(9Z)-hexadec-9-enoic"

[c16t9]
common_name = ["Palmitelaidic"]
systematic = "(9E)-hexadec-9-enoic"

[c16c6c10c14]
common_name = ["Hiragonic"]
systematic = "(6Z,10Z,14Z)-hexadeca-6,10,14-trienoic"

[c16c7c10c13]
common_name = ["Roughanic"]
systematic = "(7Z,10Z,13Z)-hexadeca-7,10,13-trienoic"

[c17]
common_name = ["Margaric"]
systematic = "heptadecanoic"

[c17c8]
common_name = ["Civetic"]
systematic = "(8Z)-heptadec-8-enoic"

[c17a8t10]
common_name = ["Pyrulic"]
systematic = "(10E)-heptadec-10-en-8-ynoic"

[c17c8c11]
common_name = ["Norlinoleic"]
systematic = "(8Z,11Z)-heptadeca-8,11-dienoic"

[c17c8c11c14]
common_name = ["Norlinolenic"]
systematic = "(8Z,11Z,14Z)-heptadeca-8,11,14-trienoic"

[c18]
common_name = ["Stearic"]
systematic = "octadecanoic"

[c18c10]
common_name = ["Isooleic"]
systematic = "(10Z)-octadec-10-enoic"

[c18c11]
common_name = ["Asclepic", "cis-Vaccenic"]
systematic = "(11Z)-octadec-11-enoic"

[c18t11]
common_name = ["Vaccenic"]
systematic = "(11E)-octadec-11-enoic"

[c18t5]
common_name = ["Thalictric"]
systematic = "(5E)-octadec-5-enoic"

[c18a6]
common_name = ["Tariric"]
systematic = "octadec-6-ynoic"
[c18c6]
common_name = ["Petroselinic"]
systematic = "(6Z)-octadec-6-enoic"

[c18t6]
common_name = ["Petroselaidic"]
systematic = "(6E)-octadec-6-enoic"

[c18a9]
common_name = ["Stearolic"]
systematic = "octadeca-9-ynoic"

[c18c9]
common_name = ["Oleic"]
systematic = "(9Z)-octadec-9-enoic"

[c18t9]
common_name = ["Elaidic"]
systematic = "(9E)-octadec-9-enoic"

[c18t10t12]
common_name = ["Mikusch's"]
systematic = "(10E,12E)-octadeca-10,12-dienoic"

[c18t11c15]
common_name = ["Vaccelenic"]
systematic = "(11E,15Z)-octadeca-11,15-dienoic"

[c18c5c11]
common_name = ["Ephedrenic"]
systematic = "(5Z,11Z)-octadeca-5,11-dienoic"

[c18c5c8]
common_name = ["Sebaleic"]
systematic = "(5Z,8Z)-octadeca-5,8-dienoic"

[c18c5c9]
common_name = ["Taxoleic"]
systematic = "(5Z,9Z)-octadeca-5,9-dienoic"

[c18e5e6]
common_name = ["Laballenic"]
systematic = "(5Ra)-octadeca-5,6-dienoic"

[c18a6e17]
common_name = ["Alvaradoic"]
systematic = "octadec-17-en-6-ynoic"

[c18c6c11]
common_name = ["Cilienic"]
systematic = "(6Z,11Z)-octadeca-6,11-dienoic"

[c18a8c10]
common_name = ["Xionenynic"]
systematic = "(10Z)-octadec-10-en-8-ynoic"

[c18a8e17]
common_name = ["Alvaradonic"]
systematic = "octadec-17-en-8-ynoic"

[c18a9t11]
common_name = ["Agonandoic", "Ximenynic"]
systematic = "(11E)-octadec-11-en-9-ynoic"

[c18c9c11]
common_name = ["Ricinenic"]
systematic = "(9Z,11Z)-octadeca-9,11-dienoic"

[c18c9t11]
common_name = ["Rumenic"]
systematic = "(9Z,11E)-octadeca-9,11-dienoic"

[c18c9a12]
common_name = ["Crepenynic"]
systematic = "(9Z)-octadec-9-en-12-ynoic"

[c18c9c12]
common_name = ["Linoleic"]
systematic = "(9Z,12Z)-octadeca-9,12-dienoic"

[c18t9t11]
common_name = ["Mangold's"]
systematic = "(9E,11E)-octadeca-9,11-dienoic"

[c18t9t12]
common_name = ["Linelaidic"]
systematic = "(9E,12E)-octadeca-9,12-dienoic"

[c18t10t12t14]
common_name = ["Pseudoeleostearic"]
systematic = "(10E,12E,14E)-octadeca-10,12,14-trienoic"

[c18t3c9c12]
common_name = ["Caleic"]
systematic = "(3E,9Z,12Z)-octadeca-3,9,12-trienoic"

[c18c5c9c12]
common_name = ["Pinolenic"]
systematic = "(5Z,9Z,12Z)-octadeca-5,9,12-trienoic"

[c18r5e6c16]
common_name = ["R-Lamenallenic"]
systematic = "(5R,16E)-octadeca-5,6,16-trienoic"

[c18s5e6c16]
common_name = ["S-Lamenallenic"]
systematic = "(5S,16E)-octadeca-5,6,16-trienoic"

[c18t5c9c12]
common_name = ["Columbinic"]
systematic = "(5E,9Z,12Z)-octadeca-5,9,12-trienoic"

[c18c6c9c12]
common_name = ["GLA"]
systematic = "(6Z,9Z,12Z)-octadeca-6,9,12-trienoic"

[c18c8c10c12]
common_name = ["β-Calendic"]
systematic = "(8Z,10Z,12Z)-octadeca-8,10,12-trienoic"

[c18c8c10t12]
common_name = ["α-Calendic"]
systematic = "(8Z,10Z,12E)-octadeca-8,10,12-trienoic"

[c18c8t10c12]
common_name = ["Jacaranda"]
systematic = "(8Z,10E,12Z)-octadeca-8,10,12-trienoic"

[c18a9a11c13]
common_name = ["Bolekic"]
systematic = "(13Z)-octadec-13-ene-9,11-diynoic"

[c18a9a11t13]
common_name = ["Exocarpic"]
systematic = "(13E)-octadec-13-ene-9,11-diynoic"

[c18a9a11e17]
common_name = ["Isanic"]
systematic = "17-octadecene-9,11-diynoic"

[c18c9t11c13]
common_name = ["Punicic"]
systematic = "(9Z,11E,13Z)-octadeca-9,11,13-trienoic"

[c18c9t11t13]
common_name = ["α-Eleostearic"]
systematic = "(9Z,11E,13E)-octadeca-9,11,13-trienoic"

[c18c9t11c15]
common_name = ["Rumelenic"]
systematic = "(9Z,11E,15Z)-octadeca-9,11,15-trienoic"

[c18c9a12c14]
common_name = ["Dehydrocrepenynic"]
systematic = "(9Z,14Z)-octadeca-9,14-dien-12-ynoic"

[c18c9c12c15]
common_name = ["α-Linolenic"]
systematic = "(9Z,12Z,-15Z)-octadeca-9,12,15-trienoic"

[c18c9t13c15]
common_name = ["Isorumelenic"]
systematic = "(9Z,13E,15Z)-octadeca-9,13,15-trienoic"

[c18t9t11c13]
common_name = ["Catalpic"]
systematic = "(9E,11E,13Z)-octadeca-9,11,13-trienoic"

[c18t9t11t13]
common_name = ["β-Eleostearic"]
systematic = "(9E,11E,13E)-octadeca-9,11,13-trienoic"

[c18t9t12t15]
common_name = ["Linolenelaidic"]
systematic = "(9E,12E,15E)-octadeca-9,12,15-trienoic"

[c18c5c9c12c15]
common_name = ["Coniferonic"]
systematic = "(5Z,9Z,12Z,15Z)-octadeca-5,9,12,15-tetraenoic"

[c18a6c9c12c15]
common_name = ["Dicramin"]
systematic = "(9Z,12Z,15Z)-octadeca-9,12,15-trien-6-ynoic"

[c18c6c9c12c15]
common_name = ["Stearidonic"]
systematic = "(6Z,9Z,12Z,15Z)-octadeca-6,9,12,15-tetraenoic"

[c18c8c10c12t14]
common_name = ["Ixoric"]
systematic = "(8Z,10Z,12Z,14E)-octadeca-8,10,12,14-tetraenoic"

[c18c9t11t13c15]
common_name = ["α-Parinaric"]
systematic = "(9Z,11E,13E,15Z)-octadeca-9,11,13,15-tetraenoic"

[c18t9t11t13t15]
common_name = ["β-Parinaric"]
systematic = "(9E,11E,13E,15E)-octadeca-9,11,13,15-tetraenoic"

[c20]
common_name = ["Arachidic"]
systematic = "icosanoic"

[c20c11]
common_name = ["Gondoic"]
systematic = "(11Z)-icos-11-enoic"

[c20c13]
common_name = ["Paullinic"]
systematic = "(13E)-icos-13-enoic"

[c20c9]
common_name = ["Gadoleic", "Gondoleic"]
systematic = "(9Z)-icos-9-enoic"

[c20t9]
common_name = ["Gadelaidic"]
systematic = "(9E)-icos-9-enoic"

[c20c11c14]
common_name = ["Dihomolinoleic"]
systematic = "(11Z,14Z)-icosa-11,14-dienoic"

[c20c5c11]
common_name = ["Keteleeronic"]
systematic = "(5Z,11Z)-icosa-5,11-dienoic"

[c20c7c11]
common_name = ["Dihomotaxoleic"]
systematic = "(7Z,11Z)-icosa-7,11-dienoic"

[c20e7e8]
common_name = ["Phlomic"]
systematic = "(7Ra)-icosa-7,8-dienoic"

[c20c11c14c17]
common_name = ["Dihomolinolenic"]
systematic = "(11Z,14Z,17Z)-icosa-11,14,17-trienoic"

[c20c5c11c14]
common_name = ["Sciadonic", "Sciadopinolenic", "Podocarpic"]
systematic = "(5Z,11Z,14Z)-icosa-5,11,14-trienoic"

[c20c5c8c11]
common_name = ["Mead"]
systematic = "(5Z,8Z,11Z)-icosa-5,8,11-trienoic"

[c20c7c11c14]
common_name = ["Bishomopinolenic", "Dihomopinolenic"]
systematic = "(7Z,11Z,14Z)-icosa-7,11,14-trienoic"

[c20c7c11t14]
common_name = ["Bishomocolumbinic"]
systematic = "(7Z,11Z,14E)-icosa-7,11,14-trienoic"

[c20c8c11c14]
common_name = ["Bishomo-γ-linolenic", "Dihomo-γ-linolenic"]
systematic = "(8Z,11Z,14Z)-icosa-8,11,14-trienoic"

[c20c4c8c12c15]
common_name = ["Moroctic"]
systematic = "(4Z,8Z,12Z,15Z)-icosa-4,7,12,15-tetraenoic"

[c20c5c11c14c17]
common_name = ["Juniperonic"]
systematic = "(5Z,11Z,14Z,17Z)-icosa-5,11,14,17-tetraenoic"

[c20c5c8c11c14]
common_name = ["Arachidonic"]
systematic = "(5Z,8Z,11Z,14Z)-icosa-5,8,11,14-tetraenoic"

[c20c5c8t10t12c14]
common_name = ["Bosseopentaenoic"]
systematic = "(5Z,8Z,10E,12E,14Z)-icosa-5,8,10,12,14-pentaenoic"

[c20c5c8c11c14c17]
common_name = ["EPA"]
systematic = "(5Z,8Z,11Z,14Z,17Z)-icosa-5,8,11,14,17-pentaenoic"

[c22]
common_name = ["Behenic"]
systematic = "docosanoic"

[c22c11]
common_name = ["Cetoleic"]
systematic = "(11Z)-docos-11-enoic"

[c22t11]
common_name = ["Cetelaidic"]
systematic = "(11E)-docos-11-enoic"

[c22a13]
common_name = ["Behenolic"]
systematic = "docos-13-ynoic"

[c22c13]
common_name = ["Erucic"]
systematic = "(13Z)-docos-13-enoic"

[c22t13]
common_name = ["Brassidic"]
systematic = "(13E)-docos-13-enoic"

[c22c5c13c16]
common_name = ["Eranthic"]
systematic = "(5Z,13Z,16Z)-docosa-5,13,16-trienoic"

[c22c7c10c13]
common_name = ["Dihomo Mead's"]
systematic = "(7Z,10Z,13Z)-docosa-7,10,13-trienoic"

[c22c7c10c13c16]
common_name = ["Adrenic"]
systematic = "(7Z,10Z,13Z,16Z)-docosa-7,10,13,16-tetraenoic"

[c22c4c8c12c15c19]
common_name = ["Clupadonic"]
systematic = "(4Z,8Z,12Z,15Z,19Z)-docosa-4,8,12,15,19-pentaenoic"

[c22c7c10c13c16c19]
common_name = ["DPA"]
systematic = "(7Z,10Z,13Z,16Z,19Z)-docosa-7,10,13,16,19-pentaenoic"

[c22c4c7c10c13c16c19]
common_name = ["DHA"]
systematic = "(4Z,7Z,10Z,13Z,16Z,19Z)-docosa-4,7,10,13,16,19-hexaenoic"

[c24]
common_name = ["Lignoceric"]
systematic = "tetracosanoic"

[c24c15]
common_name = ["Nervonic"]
systematic = "(15Z)-tetracos-15-enoic"

[c24t15]
common_name = ["trans-Selacholeic"]
systematic = "(15E)-tetracos-=15-enoic"

[c24c6c9c12c15c18c21]
common_name = ["Nisinic"]
systematic = "(6Z,9Z,12Z,15Z,18Z,21Z)-tetracosa- 6,9,12,15,18,21-hexaenoic"

[c25]
common_name = ["Hyenic"]
systematic = "pentacosanoic"

[c26]
common_name = ["Cerotic"]
systematic = "hexacosanoic"

[c26c17]
common_name = ["Ximenic"]
systematic = "(17Z)-hexacos-17-enoic"

[c26c11c14c17c20c23]
common_name = ["Shibic"]
systematic = "(11Z,14Z,17Z,20Z,23Z)-hexacosa-11,14,17,20,23-pentaenoic"

[c26e0e0e0e0e0e0]
common_name = ["Thynnic"]
systematic = "hexacosahexaenoic"

[c27]
common_name = ["Carboceric"]
systematic = "heptacosanoic"

[c28]
common_name = ["Montanic"]
systematic = "octacosanoic"

[c30]
common_name = ["Melissic"]
systematic = "triacontanoic"

[c30c21]
common_name = ["Lumequeic"]
systematic = "(21Z)-triacont-21-enoic"

[c32]
common_name = ["Lacceric"]
systematic = "dotriacontanoic"

[c33]
common_name = ["Psyllic"]
systematic = "tritriacontanoic"

[c34]
common_name = ["Gheddic"]
systematic = "tetratriacontanoic"

[c35]
common_name = ["Ceroplastic"]
systematic = "pentatriacontanoic"
